### ISSUE TITLE
XP12 - Throttles idle during mach speed

### ISSUE THREAD

**Issue by NNowakowski** [olejorga/otto-throttle#3]
I've just started using the plugin in XP12 for simulating an autothrottle in the CRJ series.
It's working pretty darn well, thanks for that!
I have however encounter an issue when switching over to mach units.
During cruise I set a mach speed of 0.78 for example, but as soon as I do this, the plugin decreases the throttles to idle.

I've looked into the CPP code a bit to evaluate the datarefs that you're using and figured out, that the dataref indicated_airspeed *always* displays the speed in kts, while the dataref airspeed_dial_kts_mach *toggles* between kts and mach, depending on the current setting in the aircraft.

![image](https://github.com/olejorga/otto-throttle/assets/16933892/6d15ef34-c9e2-4884-a9a5-fcb55341b79d)
![image](https://github.com/olejorga/otto-throttle/assets/16933892/a0b0c742-d24c-442c-9add-aafcfe44c7b9)

Switching over from airspeed_dial_kts_mach to airspeed_dial_kts should solve this issue, as it would always compare kts numbers on both sides of the equation.

Can you provide an update for the CPP version? Alternatively, how far behind is the FlyWithLua version of the plugin compared to the CPP counterpart? That way I could correct the tracked dataref myself if that's easier.

**Comment by olejorga** [comment]
Hi, I had almost forgot about this plugin!

I see, makes sense. I haven't flown X-Plane in years sadly, so updating this plugin was not on the books. However, I'll see if I can cook something up this weekend (if I can find the time).

As for the similarities between the CPP-version and lua-version, the logic should be identical. As far as I can remember, the only thing I did was to write the same logic using CPP and the X-Plane SDK instead. That being said, I did a quick comparison and I cannot see any immediate differences. The logic and granularity of the throttle adjustment are the same.

So feel free to correct the lua 👍 
Please add the corrected lua-version to the repo as well, I am guessing others have the problem too.

Thanks for letting me know, 
and I wish you a great day 🥇
